### ISSUE TITLE
Querying PAIRS resulted in HTML error code '500'

### ISSUE THREAD

**Issue by mehdiselbi** [IBM/ibmpairs#3]
hi there,
I'm trying to execute the IBM PAIRS API wrapper tutorial notebook and this error occurs when executing the 13th cell with the following message:
"ERROR - 2019-06-24 14:14:13,227: "Unable to load point data into dataframe: 'Querying PAIRS resulted in HTML error code '500': {}.'." [submit]"
any idea on how to resolve the problem?
I've tried to change the point data and the date and it didn't work! 
Thanks in advanced

**Comment by cmalbrec** [comment]
Hi @mehdiselbi :

It seems an issue with the permissions of your account. I am updating the tutorial soon with some new features and a dataset/layer that you will definitely have access to. I just need to get through some administration. Stay tuned ...

Conrad

**Comment by cmalbrec** [comment]
Hi @mehdiselbi :

Since it has been a while and I still need to wait for some aspects before I can release the next PAW version, pls try the latest tutorial in the development branch: https://github.com/IBM/ibmpairs/blob/develop/tutorials/IBM-PAIRS-API-wrapper-tutorial.ipynb along with the latest installation (`pip install git+https://github.com/ibm/ibmpairs@develop`) and pls let me know if that works for you now.

**Comment by cmalbrec** [comment]
Hi @mehdiselbi: 

Release https://github.com/IBM/ibmpairs/releases/tag/v0.0.6 should have solved your issue. I am closing for now - please reopen if that is not the case.
